Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "HT_2.P1"
        vb.memory = "512"
        config.vm.network "forwarded_port", guest: 80, host: 8080
        config.vm.network "forwarded_port", guest: 81, host: 8081
    end

    config.vm.provision "file", run: "always", source: "index.html", destination: "/tmp/index.html"
    config.vm.provision "file", run: "always", source: "index.php", destination: "/tmp/index.php"
    config.vm.provision "file", run: "always", source: "static.conf", destination: "/tmp/static.conf"
    config.vm.provision "file", run: "always", source: "dynamic.conf", destination: "/tmp/dynamic.conf"

    config.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2
        apt install -y php
        mkdir -p /var/www/static
        mkdir -p /var/www/dynamic
        mv /tmp/index.html /var/www/static/index.html
        mv /tmp/index.php /var/www/dynamic/index.php
        mv /tmp/static.conf /etc/apache2/sites-available/static.conf
        mv /tmp/dynamic.conf /etc/apache2/sites-available/dynamic.conf
        a2dissite 000-default.conf
        a2ensite static.conf
        a2ensite dynamic.conf
        sed -i '/Listen 80/a Listen 81' /etc/apache2/ports.conf
        systemctl restart apache2
    SHELL
end
