unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope:    GLOBAL
              id:       nexus-creds
              username: uploader
              password: uploader
          - usernamePassword:
              scope: GLOBAL
              id: staging-creds
              username: vagrant
              password: vagrant
          - usernamePassword:
              scope: GLOBAL
              id: prod-creds
              username: vagrant
              password: vagrant

tool:
  go:
    installations:
    - name: "go_lang"
      properties:
      - installSource:
          installers:
          - golangInstaller:
              id: "1.16"