---
version: '2.4'
services:
  nexus:
    build: ./nexus
    image: nexus
    tty: true
    stdin_open: true
    networks:
      - wcg-pipeline
    ports:
      - "81:8081"
    healthcheck:
      test: curl -f http://localhost:8081||exit1
      interval: 20s
      timeout: 10s
      retries: 4
  jenkins:
    build: ./jenkins
    image: jenkins
    networks:
      - wcg-pipeline
    depends_on:
      nexus:
        condition: service_healthy
    ports:
      - "80:8080"

networks:
  wcg-pipeline: {}