FROM golang:1.16 AS builder
WORKDIR /tmp/world-cloud-generator
RUN git clone https://github.com/Fenikks/word-cloud-generator.git /tmp/world-cloud-generator
RUN make

FROM alpine:latest
RUN apk update && apk add libc6-compat
COPY --from=builder /tmp/world-cloud-generator/artifacts/linux/word-cloud-generator /opt/word-cloud-generator
EXPOSE 8888
ENTRYPOINT /opt/word-cloud-generator