---
- name: Touch the file, but add/remove some permissions
  hosts: node2
  become: true
  tasks:
  - file:
      path: '{{ item.fpath }}'
      state: file
      owner: vagrant
      mode: u+rw,g-rwx,o-rwx
    loop:
      - { fpath: /home/vagrant/private_key_node0 }
      - { fpath: /home/vagrant/private_key_node1 }

  - name: install packages
    apt:
      pkg:
        - nginx
        - php-fpm
      update_cache: true
      state: present

  - name: delete nginx default conf file
    ansible.builtin.file:
      path: /etc/nginx/sites-available/default
      state: absent
    notify: reload nginx

  - name: copy nginx conf file
    copy:
      src: /vagrant/nginx.conf
      dest: /etc/nginx/sites-available/default
    notify: reload nginx

  handlers:
    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

- name: Node0 config
  hosts: node0
  become: true
  tasks:
  - name: install packages
    apt:
      pkg:
        - apache2
      update_cache: true
      state: present

  - name: Creates directory static
    file:
      path: /var/www/static
      state: directory

  - name: copy apache2 conf files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - src: /vagrant/index.html
        dest: /var/www/static
      - src: /vagrant/static.conf
        dest: /etc/apache2/sites-available

  - name: enable static site
    command: "/usr/sbin/a2ensite static.conf"
    notify: reload Apache

  - name: disable default Apache site
    command: "/usr/sbin/a2dissite 000-default.conf"
    notify: reload Apache

  handlers:
    - name: reload Apache
      ansible.builtin.service:
        name: apache2
        state: reloaded

- name: Node1 config
  hosts: node1
  become: true
  tasks:
  - name: install packages
    apt:
      pkg:
        - apache2
        - php
      update_cache: true
      state: present

  - name: Creates directory dynamic
    file:
      path: /var/www/dynamic
      state: directory

  - name: copy apache2 conf files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - src: /vagrant/index.php
        dest: /var/www/dynamic
      - src: /vagrant/dynamic.conf
        dest: /etc/apache2/sites-available

  - name: enable static site
    command: "/usr/sbin/a2ensite dynamic.conf"
    notify: reload Apache

  - name: disable default Apache site
    command: "/usr/sbin/a2dissite 000-default.conf"
    notify: reload Apache

  handlers:
    - name: reload Apache
      ansible.builtin.service:
        name: apache2
        state: reloaded