Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "512"
	end

    config.vm.define "node0" do |node|
        node.vm.network "private_network", ip: "192.168.50.2"
    end

    config.vm.define "node1" do |node|
        node.vm.network "private_network", ip: "192.168.50.3"
    end

    config.vm.define "node2" do |node|
        node.vm.network "private_network", ip: "192.168.50.4"

        node.vm.provision :file, source: '.vagrant/machines/node0/virtualbox/private_key', destination: '/home/vagrant/private_key_node0'
        node.vm.provision :file, source: '.vagrant/machines/node1/virtualbox/private_key', destination: '/home/vagrant/private_key_node1'

        node.vm.provision :ansible_local do |ansible|
            ansible.playbook       = "playbook.yml"
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end