---
- name: Master provision
  hosts: master
  become: true

  tasks:
  - name: install packages
    apt:
      pkg:
      - apache2
      - php
      update_cache: true
      state: present

  - name: Creates directory
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - /var/www/static
      - /var/www/dynamic

  - name: copy multiple items
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - src: /vagrant/index.html
        dest: /var/www/static
      - src: /vagrant/index.php
        dest: /var/www/dynamic
      - src: /vagrant/static.conf
        dest: /etc/apache2/sites-available/static.conf
      - src: /vagrant/dynamic.conf
        dest: /etc/apache2/sites-available/dynamic.conf

  - name: enable static site
    command: "/usr/sbin/a2ensite static.conf"
    notify: reload Apache

  - name: enable dynamic site
    command: "/usr/sbin/a2ensite dynamic.conf"
    notify: reload Apache

  - name: disable default Apache site
    command: "/usr/sbin/a2dissite 000-default.conf"
    notify: reload Apache

  - name: config ports
    lineinfile:
      dest: "/etc/apache2/ports.conf"
      insertafter: 'Listen 80'
      line: "Listen 81"
      state: present

  handlers:
    - name: reload Apache
      ansible.builtin.service:
        name: apache2
        state: reloaded