Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.name = "HT_3.P1"
        vb.memory = "512"
        config.vm.network "forwarded_port", guest: 80, host: 8080
        config.vm.network "forwarded_port", guest: 81, host: 8081
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "master.yaml"
        ansible.limit = 'all'
        ansible.inventory_path = "inventory"
    end
end