Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    #config.vm.provider "virtualbox" do |vb|
    #    vb.memory = 512
    #    vb.cpus   = 1
    #end

    config.vm.define "staging.vm", primary: true do |staging|
        staging.vm.network "private_network", ip: "192.168.50.4"
        staging.vm.hostname = "staging.vm"
        staging.vm.provider("virtualbox") { |vb| vb.memory = 256 }
        staging.vm.provider("virtualbox") { |vb| vb.cpus = 1 }

        staging.vm.provision "shell", inline: <<-SHELL
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
            echo -e "vagrant\nvagrant" | passwd vagrant
        SHELL
    end

    config.vm.define "production.vm", primary: true do |production|
        production.vm.network "private_network", ip: "192.168.50.5"
        production.vm.hostname = "production.vm"
        production.vm.provider("virtualbox") { |vb| vb.memory = 256 }
        production.vm.provider("virtualbox") { |vb| vb.cpus = 1 }

        production.vm.provision "shell", inline: <<-SHELL
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
            echo -e "vagrant\nvagrant" | passwd vagrant
        SHELL
    end

    config.vm.define "nexus.vm", primary: true do |nexus|
        nexus.vm.network "private_network", ip: "192.168.50.3"
        nexus.vm.hostname = "nexus.vm"
        nexus.vm.provider("virtualbox") { |vb| vb.memory = 2048 }
        nexus.vm.provider("virtualbox") { |vb| vb.cpus = 2 }
    end

    config.vm.define "jenkins.vm", primary: true do |jenkins|
        jenkins.vm.network "private_network", ip: "192.168.50.2"
        jenkins.vm.hostname = "master.jenkins"
        jenkins.vm.provider("virtualbox") { |vb| vb.memory = 2048 }
        jenkins.vm.provider("virtualbox") { |vb| vb.cpus = 2 }

        jenkins.vm.provision :file, source: '.vagrant/machines/nexus.vm/virtualbox/private_key', destination: '/home/vagrant/private_key_nexus.vm'
        jenkins.vm.provision :file, source: '.vagrant/machines/staging.vm/virtualbox/private_key', destination: '/home/vagrant/private_key_staging.vm'
        jenkins.vm.provision :file, source: '.vagrant/machines/production.vm/virtualbox/private_key', destination: '/home/vagrant/private_key_production.vm'

        jenkins.vm.provision :ansible_local do |ansible|
            ansible.galaxy_role_file = "requirements.yml"
            ansible.galaxy_roles_path = "/etc/ansible/roles"
            ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
            ansible.playbook       = "playbook.yml"
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end
