service:
  name: wcg
  port: 8888

container:
  label: wcg
  port: 8888
  name: wcg

replicas: 1

image:
  repository: 'ghcr.io/paveldolbik92/wcg'
  tag: latest

ingress:
  host: 'wcg.app.local'
  path: /
  pathType: Prefix