name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}

      - name: "Echo new_tag"
        run: |
          echo "${{ steps.tag_version.outputs.new_tag }}"

      - name: "Echo previous_tag"
        run: |
          echo "${{ steps.tag_version.outputs.previous_tag }}"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Helm process
        uses: |
          helm package 14-argocd/wcg-helm-chart --version 1.0 --app-version 1.0 -d charts
          helm repo index .

      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v4