name: Create and publish a WCG-APP Docker image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wcg
  BUILD_VERSION: 9

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    #permissions:
      #contents: read
      #packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: owner_string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository_owner }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./07-docker/
          push: true
          file: ./14-argocd/Dockerfile.multi
          build-args: BUILD_VERSION=${{ env.BUILD_VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ steps.owner_string.outputs.lowercase }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}
